version: "3.4"

services:
  basket-db:
    image: postgres
  
  catalogue-db:
    image: postgres
  
  distributed-cache:
    image: redis
  
  #    order-db:
  #        image: mcr.microsoft.com/mssql/server:2022-latest
  #        platform: linux/amd64
  
  order-db:
    image: postgres
  
  message-broker:
    image: rabbitmq:management
  
  yarp-api-gateway:
    container_name: yarp-api-gateway
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: ./src
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile
  
  basket.api:
    container_name: basket.api
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: ./src
      dockerfile: Services/Basket/Basket.Api/Dockerfile
  
  catalogue.api:
    container_name: catalogue.api
    image: ${DOCKER_REGISTRY-}catalogueapi
    build:
      context: .
      dockerfile: src/Services/Catalogue/Catalogue.Api/Dockerfile
  
  discount.grpc:
    container_name: discount.grpc
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: src/Services/Discount/Discount.Grpc/Dockerfile
  
  ordering.api:
    container_name: ordering.api
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: ./src
      dockerfile: Services/Ordering/Ordering.Api/Dockerfile

volumes:
  postgres_basket:
  postgres_catalogue:
  postgres_ordering:
