version: '3.4'

services:
  basketdb:
    image: postgres

  cataloguedb:
    image: postgres
  
  distributedcache:
    image: redis
  
  basket.api:
    container_name: basket.api
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.Api/Dockerfile
  
  catalogue.api:
    container_name: catalogue.api
    image: ${DOCKER_REGISTRY-}catalogueapi
    build:
      context: .
      dockerfile: src/Services/Catalogue/Catalogue.Api/Dockerfile
  
  discount.grpc:
    container_name: discount.grpc
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: src/Services/Discount/Discount.Grpc/Dockerfile

volumes:
  postgres_basket:
  postgres_catalogue:
